name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'record.py'
      - 'requirements.txt'
      - 'record.Dockerfile'
      - 'record-lite.Dockerfile'
      - '.github/workflows/docker-image.yml'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        cuda: [ "13.1.0-runtime-ubuntu24.04", 12.9.1-cudnn-runtime-ubuntu24.04 ]
    environment:
      name: Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: |
          atmaranto/record:lite
          atmaranto/record:${{ github.run_number }}-lite
          atmaranto/record:lite-cuda${{ matrix.cuda }}
          atmaranto/record:${{ github.run_number }}-lite-cuda${{ matrix.cuda }}
        build-args: |
          IMAGE_VERSION=${{ matrix.cuda }}
        file: record-lite.Dockerfile
        context: .
    - uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: |
          atmaranto/record:latest
          atmaranto/record:${{ github.run_number }}
          atmaranto/record:cuda${{ matrix.cuda }}
          atmaranto/record:${{ github.run_number }}-cuda${{ matrix.cuda }}
        build-args: |
          IMAGE_VERSION=${{ matrix.cuda }}
        file: record.Dockerfile
        context: .
    - uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: |
          atmaranto/record:no-transcription
          atmaranto/record:${{ github.run_number }}-no-transcription
          atmaranto/record:no-transcription-cuda${{ matrix.cuda }}
          atmaranto/record:${{ github.run_number }}-no-transcription-cuda${{ matrix.cuda }}
        build-args: |
          IMAGE_VERSION=${{ matrix.cuda }}
        file: no-transcription.Dockerfile
        context: .
    