name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'record.py'
      - 'requirements.txt'
      - 'record.Dockerfile'
      - 'record-lite.Dockerfile'
      - '.github/workflows/docker-image.yml'
  workflow_dispatch:

jobs:
  build:
    environment:
      name: Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: |
          atmaranto/record:lite
          atmaranto/record:${{ github.run_number }}-lite
        file: record-lite.Dockerfile
        context: .
    - uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: |
          atmaranto/record:latest
          atmaranto/record:${{ github.run_number }}
        file: record.Dockerfile
        context: .
    - uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: |
          atmaranto/record:no-transcription
          atmaranto/record:${{ github.run_number }}-no-transcription
        file: no-transcription.Dockerfile
        context: .
    